from .base import ServiceBase
from .auth import *
from .usuario import *
from .docente import *
from .estudiante import *
from .curso import *
from .contenido import *
from .evaluacion import *
from .ejercicio import *
from .actividad import *
from .gamificacion import *
from .estadisticas import *
from .padre import *